FROM node:20-alpine

WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./

COPY .yarn ./.yarn

RUN yarn install --immutable

COPY . .

RUN yarn prisma generate
RUN yarn build

EXPOSE 3000
CMD ["node", "dist/src/main.js"]